rust_glue.o: rust_glue.cpp userspace-vdp-gl/src/fabutils.h \
  userspace-vdp-gl/src/userspace-platform/fake_fabgl.h \
  userspace-vdp-gl/src/userspace-platform/freertos/FreeRTOS.h \
  userspace-vdp-gl/src/userspace-platform/HardwareSerial.h \
  userspace-vdp-gl/src/userspace-platform/Stream.h \
  userspace-vdp-gl/src/fabgl.h userspace-vdp-gl/src/fabfonts.h \
  userspace-vdp-gl/src/fabglconf.h \
  userspace-vdp-gl/src/userspace-platform/esp_wifi.h \
  userspace-vdp-gl/src/fonts/font_4x6.h \
  userspace-vdp-gl/src/fonts/font_5x7.h \
  userspace-vdp-gl/src/fonts/font_5x8.h \
  userspace-vdp-gl/src/fonts/font_6x8.h \
  userspace-vdp-gl/src/fonts/font_6x9.h \
  userspace-vdp-gl/src/fonts/font_6x10.h \
  userspace-vdp-gl/src/fonts/font_6x12.h \
  userspace-vdp-gl/src/fonts/font_6x13.h \
  userspace-vdp-gl/src/fonts/font_7x13.h \
  userspace-vdp-gl/src/fonts/font_7x14.h \
  userspace-vdp-gl/src/fonts/font_8x13.h \
  userspace-vdp-gl/src/fonts/font_8x8.h \
  userspace-vdp-gl/src/fonts/font_8x9.h \
  userspace-vdp-gl/src/fonts/font_8x14.h \
  userspace-vdp-gl/src/fonts/font_8x16.h \
  userspace-vdp-gl/src/fonts/font_8x19.h \
  userspace-vdp-gl/src/fonts/font_9x15.h \
  userspace-vdp-gl/src/fonts/font_9x18.h \
  userspace-vdp-gl/src/fonts/font_10x20.h \
  userspace-vdp-gl/src/fonts/font_slant_8x14.h \
  userspace-vdp-gl/src/fonts/font_sanserif_8x16.h \
  userspace-vdp-gl/src/fonts/font_sanserif_8x14.h \
  userspace-vdp-gl/src/fonts/font_lcd_8x14.h \
  userspace-vdp-gl/src/fonts/font_courier_8x14.h \
  userspace-vdp-gl/src/fonts/font_computer_8x14.h \
  userspace-vdp-gl/src/fonts/font_bigserif_8x14.h \
  userspace-vdp-gl/src/fonts/font_bigserif_8x16.h \
  userspace-vdp-gl/src/fonts/font_block_8x14.h \
  userspace-vdp-gl/src/fonts/font_broadway_8x14.h \
  userspace-vdp-gl/src/fonts/font_oldengl_8x16.h \
  userspace-vdp-gl/src/fonts/font_wiggly_8x16.h \
  userspace-vdp-gl/src/fonts/font_std_12.h \
  userspace-vdp-gl/src/fonts/font_std_14.h \
  userspace-vdp-gl/src/fonts/font_std_15.h \
  userspace-vdp-gl/src/fonts/font_std_16.h \
  userspace-vdp-gl/src/fonts/font_std_17.h \
  userspace-vdp-gl/src/fonts/font_std_18.h \
  userspace-vdp-gl/src/fonts/font_std_22.h \
  userspace-vdp-gl/src/fonts/font_std_24.h \
  userspace-vdp-gl/src/terminal.h \
  userspace-vdp-gl/src/userspace-platform/freertos/task.h \
  userspace-vdp-gl/src/userspace-platform/freertos/timers.h \
  userspace-vdp-gl/src/userspace-platform/freertos/semphr.h \
  userspace-vdp-gl/src/canvas.h userspace-vdp-gl/src/displaycontroller.h \
  userspace-vdp-gl/src/userspace-platform/freertos/queue.h \
  userspace-vdp-gl/src/devdrivers/keyboard.h \
  userspace-vdp-gl/src/comdrivers/ps2controller.h \
  userspace-vdp-gl/src/comdrivers/ps2device.h \
  userspace-vdp-gl/src/devdrivers/kbdlayouts.h \
  userspace-vdp-gl/src/codepages.h userspace-vdp-gl/src/terminfo.h \
  userspace-vdp-gl/src/devdrivers/soundgen.h \
  userspace-vdp-gl/src/dispdrivers/vgacontroller.h \
  userspace-vdp-gl/src/userspace-platform/driver/gpio.h \
  userspace-vdp-gl/src/devdrivers/swgenerator.h \
  userspace-vdp-gl/src/dispdrivers/vgabasecontroller.h \
  userspace-vdp-gl/src/dispdrivers/vga2controller.h \
  userspace-vdp-gl/src/dispdrivers/vgapalettedcontroller.h \
  userspace-vdp-gl/src/dispdrivers/vga4controller.h \
  userspace-vdp-gl/src/dispdrivers/vga8controller.h \
  userspace-vdp-gl/src/dispdrivers/vga16controller.h \
  userspace-vdp-gl/src/dispdrivers/vgadirectcontroller.h \
  userspace-vdp-gl/src/devdrivers/mouse.h userspace-vdp-gl/src/scene.h \
  userspace-vdp-gl/src/collisiondetector.h vdp.h
vdp-1.03.o: vdp-1.03.cpp \
  userspace-vdp-gl/src/userspace-platform/Arduino.h \
  userspace-vdp-gl/src/userspace-platform/malloc_wrapper.h \
  userspace-vdp-gl/src/userspace-platform/fake_fabgl.h \
  userspace-vdp-gl/src/userspace-platform/freertos/FreeRTOS.h \
  userspace-vdp-gl/src/userspace-platform/HardwareSerial.h \
  userspace-vdp-gl/src/userspace-platform/Stream.h vdp-1.03.h \
  userspace-vdp-gl/src/dispdrivers/vgabasecontroller.h \
  userspace-vdp-gl/src/userspace-platform/driver/gpio.h \
  userspace-vdp-gl/src/userspace-platform/freertos/queue.h \
  userspace-vdp-gl/src/fabglconf.h \
  userspace-vdp-gl/src/userspace-platform/esp_wifi.h \
  userspace-vdp-gl/src/fabutils.h \
  userspace-vdp-gl/src/devdrivers/swgenerator.h \
  userspace-vdp-gl/src/displaycontroller.h \
  userspace-vdp-gl/src/userspace-platform/freertos/task.h \
  userspace-vdp-gl/src/fabgl.h userspace-vdp-gl/src/fabfonts.h \
  userspace-vdp-gl/src/fonts/font_4x6.h \
  userspace-vdp-gl/src/fonts/font_5x7.h \
  userspace-vdp-gl/src/fonts/font_5x8.h \
  userspace-vdp-gl/src/fonts/font_6x8.h \
  userspace-vdp-gl/src/fonts/font_6x9.h \
  userspace-vdp-gl/src/fonts/font_6x10.h \
  userspace-vdp-gl/src/fonts/font_6x12.h \
  userspace-vdp-gl/src/fonts/font_6x13.h \
  userspace-vdp-gl/src/fonts/font_7x13.h \
  userspace-vdp-gl/src/fonts/font_7x14.h \
  userspace-vdp-gl/src/fonts/font_8x13.h \
  userspace-vdp-gl/src/fonts/font_8x8.h \
  userspace-vdp-gl/src/fonts/font_8x9.h \
  userspace-vdp-gl/src/fonts/font_8x14.h \
  userspace-vdp-gl/src/fonts/font_8x16.h \
  userspace-vdp-gl/src/fonts/font_8x19.h \
  userspace-vdp-gl/src/fonts/font_9x15.h \
  userspace-vdp-gl/src/fonts/font_9x18.h \
  userspace-vdp-gl/src/fonts/font_10x20.h \
  userspace-vdp-gl/src/fonts/font_slant_8x14.h \
  userspace-vdp-gl/src/fonts/font_sanserif_8x16.h \
  userspace-vdp-gl/src/fonts/font_sanserif_8x14.h \
  userspace-vdp-gl/src/fonts/font_lcd_8x14.h \
  userspace-vdp-gl/src/fonts/font_courier_8x14.h \
  userspace-vdp-gl/src/fonts/font_computer_8x14.h \
  userspace-vdp-gl/src/fonts/font_bigserif_8x14.h \
  userspace-vdp-gl/src/fonts/font_bigserif_8x16.h \
  userspace-vdp-gl/src/fonts/font_block_8x14.h \
  userspace-vdp-gl/src/fonts/font_broadway_8x14.h \
  userspace-vdp-gl/src/fonts/font_oldengl_8x16.h \
  userspace-vdp-gl/src/fonts/font_wiggly_8x16.h \
  userspace-vdp-gl/src/fonts/font_std_12.h \
  userspace-vdp-gl/src/fonts/font_std_14.h \
  userspace-vdp-gl/src/fonts/font_std_15.h \
  userspace-vdp-gl/src/fonts/font_std_16.h \
  userspace-vdp-gl/src/fonts/font_std_17.h \
  userspace-vdp-gl/src/fonts/font_std_18.h \
  userspace-vdp-gl/src/fonts/font_std_22.h \
  userspace-vdp-gl/src/fonts/font_std_24.h \
  userspace-vdp-gl/src/terminal.h \
  userspace-vdp-gl/src/userspace-platform/freertos/timers.h \
  userspace-vdp-gl/src/userspace-platform/freertos/semphr.h \
  userspace-vdp-gl/src/canvas.h \
  userspace-vdp-gl/src/devdrivers/keyboard.h \
  userspace-vdp-gl/src/comdrivers/ps2controller.h \
  userspace-vdp-gl/src/comdrivers/ps2device.h \
  userspace-vdp-gl/src/devdrivers/kbdlayouts.h \
  userspace-vdp-gl/src/codepages.h userspace-vdp-gl/src/terminfo.h \
  userspace-vdp-gl/src/devdrivers/soundgen.h \
  userspace-vdp-gl/src/dispdrivers/vgacontroller.h \
  userspace-vdp-gl/src/dispdrivers/vga2controller.h \
  userspace-vdp-gl/src/dispdrivers/vgapalettedcontroller.h \
  userspace-vdp-gl/src/dispdrivers/vga4controller.h \
  userspace-vdp-gl/src/dispdrivers/vga8controller.h \
  userspace-vdp-gl/src/dispdrivers/vga16controller.h \
  userspace-vdp-gl/src/dispdrivers/vgadirectcontroller.h \
  userspace-vdp-gl/src/devdrivers/mouse.h userspace-vdp-gl/src/scene.h \
  userspace-vdp-gl/src/collisiondetector.h vdp.h vdp-quark103/video.ino \
  userspace-vdp-gl/src/userspace-platform/ESP32Time.h \
  vdp-quark103/agon.h vdp-quark103/agon_fonts.h \
  vdp-quark103/agon_audio.h vdp-quark103/agon_palette.h
vdp-console8.o: vdp-console8.cpp \
  userspace-vdp-gl/src/userspace-platform/Arduino.h \
  userspace-vdp-gl/src/userspace-platform/malloc_wrapper.h \
  userspace-vdp-gl/src/userspace-platform/fake_fabgl.h \
  userspace-vdp-gl/src/userspace-platform/freertos/FreeRTOS.h \
  userspace-vdp-gl/src/userspace-platform/HardwareSerial.h \
  userspace-vdp-gl/src/userspace-platform/Stream.h vdp-console8.h \
  userspace-vdp-gl/src/fabgl.h userspace-vdp-gl/src/fabutils.h \
  userspace-vdp-gl/src/fabfonts.h userspace-vdp-gl/src/fabglconf.h \
  userspace-vdp-gl/src/userspace-platform/esp_wifi.h \
  userspace-vdp-gl/src/fonts/font_4x6.h \
  userspace-vdp-gl/src/fonts/font_5x7.h \
  userspace-vdp-gl/src/fonts/font_5x8.h \
  userspace-vdp-gl/src/fonts/font_6x8.h \
  userspace-vdp-gl/src/fonts/font_6x9.h \
  userspace-vdp-gl/src/fonts/font_6x10.h \
  userspace-vdp-gl/src/fonts/font_6x12.h \
  userspace-vdp-gl/src/fonts/font_6x13.h \
  userspace-vdp-gl/src/fonts/font_7x13.h \
  userspace-vdp-gl/src/fonts/font_7x14.h \
  userspace-vdp-gl/src/fonts/font_8x13.h \
  userspace-vdp-gl/src/fonts/font_8x8.h \
  userspace-vdp-gl/src/fonts/font_8x9.h \
  userspace-vdp-gl/src/fonts/font_8x14.h \
  userspace-vdp-gl/src/fonts/font_8x16.h \
  userspace-vdp-gl/src/fonts/font_8x19.h \
  userspace-vdp-gl/src/fonts/font_9x15.h \
  userspace-vdp-gl/src/fonts/font_9x18.h \
  userspace-vdp-gl/src/fonts/font_10x20.h \
  userspace-vdp-gl/src/fonts/font_slant_8x14.h \
  userspace-vdp-gl/src/fonts/font_sanserif_8x16.h \
  userspace-vdp-gl/src/fonts/font_sanserif_8x14.h \
  userspace-vdp-gl/src/fonts/font_lcd_8x14.h \
  userspace-vdp-gl/src/fonts/font_courier_8x14.h \
  userspace-vdp-gl/src/fonts/font_computer_8x14.h \
  userspace-vdp-gl/src/fonts/font_bigserif_8x14.h \
  userspace-vdp-gl/src/fonts/font_bigserif_8x16.h \
  userspace-vdp-gl/src/fonts/font_block_8x14.h \
  userspace-vdp-gl/src/fonts/font_broadway_8x14.h \
  userspace-vdp-gl/src/fonts/font_oldengl_8x16.h \
  userspace-vdp-gl/src/fonts/font_wiggly_8x16.h \
  userspace-vdp-gl/src/fonts/font_std_12.h \
  userspace-vdp-gl/src/fonts/font_std_14.h \
  userspace-vdp-gl/src/fonts/font_std_15.h \
  userspace-vdp-gl/src/fonts/font_std_16.h \
  userspace-vdp-gl/src/fonts/font_std_17.h \
  userspace-vdp-gl/src/fonts/font_std_18.h \
  userspace-vdp-gl/src/fonts/font_std_22.h \
  userspace-vdp-gl/src/fonts/font_std_24.h \
  userspace-vdp-gl/src/terminal.h \
  userspace-vdp-gl/src/userspace-platform/freertos/task.h \
  userspace-vdp-gl/src/userspace-platform/freertos/timers.h \
  userspace-vdp-gl/src/userspace-platform/freertos/semphr.h \
  userspace-vdp-gl/src/canvas.h userspace-vdp-gl/src/displaycontroller.h \
  userspace-vdp-gl/src/userspace-platform/freertos/queue.h \
  userspace-vdp-gl/src/devdrivers/keyboard.h \
  userspace-vdp-gl/src/comdrivers/ps2controller.h \
  userspace-vdp-gl/src/comdrivers/ps2device.h \
  userspace-vdp-gl/src/devdrivers/kbdlayouts.h \
  userspace-vdp-gl/src/codepages.h userspace-vdp-gl/src/terminfo.h \
  userspace-vdp-gl/src/devdrivers/soundgen.h \
  userspace-vdp-gl/src/dispdrivers/vgacontroller.h \
  userspace-vdp-gl/src/userspace-platform/driver/gpio.h \
  userspace-vdp-gl/src/devdrivers/swgenerator.h \
  userspace-vdp-gl/src/dispdrivers/vgabasecontroller.h \
  userspace-vdp-gl/src/dispdrivers/vga2controller.h \
  userspace-vdp-gl/src/dispdrivers/vgapalettedcontroller.h \
  userspace-vdp-gl/src/dispdrivers/vga4controller.h \
  userspace-vdp-gl/src/dispdrivers/vga8controller.h \
  userspace-vdp-gl/src/dispdrivers/vga16controller.h \
  userspace-vdp-gl/src/dispdrivers/vgadirectcontroller.h \
  userspace-vdp-gl/src/devdrivers/mouse.h userspace-vdp-gl/src/scene.h \
  userspace-vdp-gl/src/collisiondetector.h vdp.h vdp-console8/video.ino \
  vdp-console8/agon.h vdp-console8/agon_keyboard.h \
  vdp-console8/vdp_protocol.h vdp-console8/agon_screen.h \
  vdp-console8/graphics.h vdp-console8/agon_fonts.h \
  vdp-console8/agon_palette.h vdp-console8/cursor.h \
  vdp-console8/viewport.h vdp-console8/sprites.h vdp-console8/vdu.h \
  vdp-console8/vdu_audio.h vdp-console8/agon_audio.h \
  vdp-console8/envelopes/volume.h vdp-console8/envelopes/frequency.h \
  vdp-console8/vdu_sys.h \
  userspace-vdp-gl/src/userspace-platform/ESP32Time.h \
  vdp-console8/vdu_sprites.h
vdp_quark104.o: vdp_quark104.cpp \
  userspace-vdp-gl/src/userspace-platform/Arduino.h \
  userspace-vdp-gl/src/userspace-platform/malloc_wrapper.h \
  userspace-vdp-gl/src/userspace-platform/fake_fabgl.h \
  userspace-vdp-gl/src/userspace-platform/freertos/FreeRTOS.h \
  userspace-vdp-gl/src/userspace-platform/HardwareSerial.h \
  userspace-vdp-gl/src/userspace-platform/Stream.h vdp_quark104.h \
  userspace-vdp-gl/src/fabgl.h userspace-vdp-gl/src/fabutils.h \
  userspace-vdp-gl/src/fabfonts.h userspace-vdp-gl/src/fabglconf.h \
  userspace-vdp-gl/src/userspace-platform/esp_wifi.h \
  userspace-vdp-gl/src/fonts/font_4x6.h \
  userspace-vdp-gl/src/fonts/font_5x7.h \
  userspace-vdp-gl/src/fonts/font_5x8.h \
  userspace-vdp-gl/src/fonts/font_6x8.h \
  userspace-vdp-gl/src/fonts/font_6x9.h \
  userspace-vdp-gl/src/fonts/font_6x10.h \
  userspace-vdp-gl/src/fonts/font_6x12.h \
  userspace-vdp-gl/src/fonts/font_6x13.h \
  userspace-vdp-gl/src/fonts/font_7x13.h \
  userspace-vdp-gl/src/fonts/font_7x14.h \
  userspace-vdp-gl/src/fonts/font_8x13.h \
  userspace-vdp-gl/src/fonts/font_8x8.h \
  userspace-vdp-gl/src/fonts/font_8x9.h \
  userspace-vdp-gl/src/fonts/font_8x14.h \
  userspace-vdp-gl/src/fonts/font_8x16.h \
  userspace-vdp-gl/src/fonts/font_8x19.h \
  userspace-vdp-gl/src/fonts/font_9x15.h \
  userspace-vdp-gl/src/fonts/font_9x18.h \
  userspace-vdp-gl/src/fonts/font_10x20.h \
  userspace-vdp-gl/src/fonts/font_slant_8x14.h \
  userspace-vdp-gl/src/fonts/font_sanserif_8x16.h \
  userspace-vdp-gl/src/fonts/font_sanserif_8x14.h \
  userspace-vdp-gl/src/fonts/font_lcd_8x14.h \
  userspace-vdp-gl/src/fonts/font_courier_8x14.h \
  userspace-vdp-gl/src/fonts/font_computer_8x14.h \
  userspace-vdp-gl/src/fonts/font_bigserif_8x14.h \
  userspace-vdp-gl/src/fonts/font_bigserif_8x16.h \
  userspace-vdp-gl/src/fonts/font_block_8x14.h \
  userspace-vdp-gl/src/fonts/font_broadway_8x14.h \
  userspace-vdp-gl/src/fonts/font_oldengl_8x16.h \
  userspace-vdp-gl/src/fonts/font_wiggly_8x16.h \
  userspace-vdp-gl/src/fonts/font_std_12.h \
  userspace-vdp-gl/src/fonts/font_std_14.h \
  userspace-vdp-gl/src/fonts/font_std_15.h \
  userspace-vdp-gl/src/fonts/font_std_16.h \
  userspace-vdp-gl/src/fonts/font_std_17.h \
  userspace-vdp-gl/src/fonts/font_std_18.h \
  userspace-vdp-gl/src/fonts/font_std_22.h \
  userspace-vdp-gl/src/fonts/font_std_24.h \
  userspace-vdp-gl/src/terminal.h \
  userspace-vdp-gl/src/userspace-platform/freertos/task.h \
  userspace-vdp-gl/src/userspace-platform/freertos/timers.h \
  userspace-vdp-gl/src/userspace-platform/freertos/semphr.h \
  userspace-vdp-gl/src/canvas.h userspace-vdp-gl/src/displaycontroller.h \
  userspace-vdp-gl/src/userspace-platform/freertos/queue.h \
  userspace-vdp-gl/src/devdrivers/keyboard.h \
  userspace-vdp-gl/src/comdrivers/ps2controller.h \
  userspace-vdp-gl/src/comdrivers/ps2device.h \
  userspace-vdp-gl/src/devdrivers/kbdlayouts.h \
  userspace-vdp-gl/src/codepages.h userspace-vdp-gl/src/terminfo.h \
  userspace-vdp-gl/src/devdrivers/soundgen.h \
  userspace-vdp-gl/src/dispdrivers/vgacontroller.h \
  userspace-vdp-gl/src/userspace-platform/driver/gpio.h \
  userspace-vdp-gl/src/devdrivers/swgenerator.h \
  userspace-vdp-gl/src/dispdrivers/vgabasecontroller.h \
  userspace-vdp-gl/src/dispdrivers/vga2controller.h \
  userspace-vdp-gl/src/dispdrivers/vgapalettedcontroller.h \
  userspace-vdp-gl/src/dispdrivers/vga4controller.h \
  userspace-vdp-gl/src/dispdrivers/vga8controller.h \
  userspace-vdp-gl/src/dispdrivers/vga16controller.h \
  userspace-vdp-gl/src/dispdrivers/vgadirectcontroller.h \
  userspace-vdp-gl/src/devdrivers/mouse.h userspace-vdp-gl/src/scene.h \
  userspace-vdp-gl/src/collisiondetector.h vdp.h vdp-quark104/video.ino \
  vdp-quark104/agon.h vdp-quark104/agon_keyboard.h \
  vdp-quark104/agon_audio.h vdp-quark104/audio_channel.h \
  vdp-quark104/types.h vdp-quark104/envelopes/volume.h \
  vdp-quark104/envelopes/frequency.h vdp-quark104/audio_sample.h \
  vdp-quark104/enhanced_samples_generator.h vdp-quark104/graphics.h \
  vdp-quark104/agon_screen.h vdp-quark104/agon_fonts.h \
  vdp-quark104/agon_palette.h vdp-quark104/cursor.h \
  vdp-quark104/viewport.h vdp-quark104/vdp_protocol.h \
  vdp-quark104/sprites.h vdp-quark104/vdu_stream_processor.h \
  vdp-quark104/vdu.h vdp-quark104/vdu_audio.h vdp-quark104/vdu_sys.h \
  userspace-vdp-gl/src/userspace-platform/ESP32Time.h \
  vdp-quark104/vdu_buffered.h vdp-quark104/buffer_stream.h \
  vdp-quark104/multi_buffer_stream.h vdp-quark104/vdu_sprites.h \
  vdp-quark104/hexload.h
vdp_electron.o: vdp_electron.cpp \
  userspace-vdp-gl/src/userspace-platform/Arduino.h \
  userspace-vdp-gl/src/userspace-platform/malloc_wrapper.h \
  userspace-vdp-gl/src/userspace-platform/fake_fabgl.h \
  userspace-vdp-gl/src/userspace-platform/freertos/FreeRTOS.h \
  userspace-vdp-gl/src/userspace-platform/HardwareSerial.h \
  userspace-vdp-gl/src/userspace-platform/Stream.h vdp_electron.h \
  userspace-vdp-gl/src/dispdrivers/vgabasecontroller.h \
  userspace-vdp-gl/src/userspace-platform/driver/gpio.h \
  userspace-vdp-gl/src/userspace-platform/freertos/queue.h \
  userspace-vdp-gl/src/fabglconf.h \
  userspace-vdp-gl/src/userspace-platform/esp_wifi.h \
  userspace-vdp-gl/src/fabutils.h \
  userspace-vdp-gl/src/devdrivers/swgenerator.h \
  userspace-vdp-gl/src/displaycontroller.h \
  userspace-vdp-gl/src/userspace-platform/freertos/task.h \
  userspace-vdp-gl/src/fabgl.h userspace-vdp-gl/src/fabfonts.h \
  userspace-vdp-gl/src/fonts/font_4x6.h \
  userspace-vdp-gl/src/fonts/font_5x7.h \
  userspace-vdp-gl/src/fonts/font_5x8.h \
  userspace-vdp-gl/src/fonts/font_6x8.h \
  userspace-vdp-gl/src/fonts/font_6x9.h \
  userspace-vdp-gl/src/fonts/font_6x10.h \
  userspace-vdp-gl/src/fonts/font_6x12.h \
  userspace-vdp-gl/src/fonts/font_6x13.h \
  userspace-vdp-gl/src/fonts/font_7x13.h \
  userspace-vdp-gl/src/fonts/font_7x14.h \
  userspace-vdp-gl/src/fonts/font_8x13.h \
  userspace-vdp-gl/src/fonts/font_8x8.h \
  userspace-vdp-gl/src/fonts/font_8x9.h \
  userspace-vdp-gl/src/fonts/font_8x14.h \
  userspace-vdp-gl/src/fonts/font_8x16.h \
  userspace-vdp-gl/src/fonts/font_8x19.h \
  userspace-vdp-gl/src/fonts/font_9x15.h \
  userspace-vdp-gl/src/fonts/font_9x18.h \
  userspace-vdp-gl/src/fonts/font_10x20.h \
  userspace-vdp-gl/src/fonts/font_slant_8x14.h \
  userspace-vdp-gl/src/fonts/font_sanserif_8x16.h \
  userspace-vdp-gl/src/fonts/font_sanserif_8x14.h \
  userspace-vdp-gl/src/fonts/font_lcd_8x14.h \
  userspace-vdp-gl/src/fonts/font_courier_8x14.h \
  userspace-vdp-gl/src/fonts/font_computer_8x14.h \
  userspace-vdp-gl/src/fonts/font_bigserif_8x14.h \
  userspace-vdp-gl/src/fonts/font_bigserif_8x16.h \
  userspace-vdp-gl/src/fonts/font_block_8x14.h \
  userspace-vdp-gl/src/fonts/font_broadway_8x14.h \
  userspace-vdp-gl/src/fonts/font_oldengl_8x16.h \
  userspace-vdp-gl/src/fonts/font_wiggly_8x16.h \
  userspace-vdp-gl/src/fonts/font_std_12.h \
  userspace-vdp-gl/src/fonts/font_std_14.h \
  userspace-vdp-gl/src/fonts/font_std_15.h \
  userspace-vdp-gl/src/fonts/font_std_16.h \
  userspace-vdp-gl/src/fonts/font_std_17.h \
  userspace-vdp-gl/src/fonts/font_std_18.h \
  userspace-vdp-gl/src/fonts/font_std_22.h \
  userspace-vdp-gl/src/fonts/font_std_24.h \
  userspace-vdp-gl/src/terminal.h \
  userspace-vdp-gl/src/userspace-platform/freertos/timers.h \
  userspace-vdp-gl/src/userspace-platform/freertos/semphr.h \
  userspace-vdp-gl/src/canvas.h \
  userspace-vdp-gl/src/devdrivers/keyboard.h \
  userspace-vdp-gl/src/comdrivers/ps2controller.h \
  userspace-vdp-gl/src/comdrivers/ps2device.h \
  userspace-vdp-gl/src/devdrivers/kbdlayouts.h \
  userspace-vdp-gl/src/codepages.h userspace-vdp-gl/src/terminfo.h \
  userspace-vdp-gl/src/devdrivers/soundgen.h \
  userspace-vdp-gl/src/dispdrivers/vgacontroller.h \
  userspace-vdp-gl/src/dispdrivers/vga2controller.h \
  userspace-vdp-gl/src/dispdrivers/vgapalettedcontroller.h \
  userspace-vdp-gl/src/dispdrivers/vga4controller.h \
  userspace-vdp-gl/src/dispdrivers/vga8controller.h \
  userspace-vdp-gl/src/dispdrivers/vga16controller.h \
  userspace-vdp-gl/src/dispdrivers/vgadirectcontroller.h \
  userspace-vdp-gl/src/devdrivers/mouse.h userspace-vdp-gl/src/scene.h \
  userspace-vdp-gl/src/collisiondetector.h vdp.h \
  vdp-electronhal/main.cpp vdp-electronhal/globals.h \
  vdp-electronhal/hal.h vdp-electronhal/zdi.h vdp-electronhal/eos.h \
  vdp-electronhal/tms9918.h vdp-electronhal/ay_3_8910.h \
  vdp-electronhal/sn76489an.h vdp-electronhal/ppi-8255.h \
  vdp-electronhal/audio_driver.h vdp-electronhal/updater.h \
  vdp-electronhal/sn76489an.cpp vdp-electronhal/audio_channel.h \
  vdp-electronhal/audio_envelopes/volume.h \
  vdp-electronhal/audio_envelopes/frequency.h vdp-electronhal/types.h \
  vdp-electronhal/tms9918.cpp vdp-electronhal/zdi.cpp \
  vdp-electronhal/OneWire_direct_gpio.h vdp-electronhal/updater.cpp \
  userspace-vdp-gl/src/userspace-platform/esp_ota_ops.h \
  vdp-electronhal/ppi-8255.cpp vdp-electronhal/mos.cpp \
  vdp-electronhal/mos.h vdp-electronhal/hal.cpp vdp-electronhal/eos.cpp \
  vdp-electronhal/ay_3_8910.cpp vdp-electronhal/ay_3_8910_noise.cpp \
  vdp-electronhal/ay_3_8910_noise.h vdp-electronhal/audio_driver.cpp \
  vdp-electronhal/audio_sample.h vdp-electronhal/audio_sample.cpp \
  vdp-electronhal/audio_enhanced_samples_generator.cpp \
  vdp-electronhal/audio_enhanced_samples_generator.h \
  vdp-electronhal/audio_channel.cpp \
  vdp-electronhal/audio_envelopes/frequency.cpp \
  vdp-electronhal/audio_envelopes/volume.cpp
